

server: 
  port: 8090
  
spring:
  cloud:
    gateway:
      routes:
      - id: ITEMS-MODULE
        uri: http://localhost:8080/
        predicates:
        - Path= /items/**
        
      - id: PRICE-MODULE
        uri: http://localhost:8081/
        predicates:
        - Path= /price/**
          
          
            
            
